service: nest-serverless-lambda-demo

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-warmup
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

custom:
  warmup:
    default:
      enabled: true
      events:
        - schedule: rate(1 minute)
        
functions:
  main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
    # warmup:
    #   default:
    #     enabled: true
